version: '3.4'

services:
  foodapp:
    image: foodapp
    container_name: foodapp
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    networks:
      - nginx_network
      
  waf:
    image: owasp/modsecurity:nginx
    container_name: waf
    depends_on:
      - foodapp
    ports: 
      - 80:80
    volumes:
      - "./etc/modsecurity:/etc/modsecurity"
      - "./etc/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf"
      - "./etc/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf"
      - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - nginx_network
    command: /bin/sh -c "exec nginx -g 'daemon off;'" 

networks:
  nginx_network:
    driver: bridge
